/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemWorkArea.Encounters;

import userinterface.SystemWorkArea.Doctor.*;
import userinterface.SystemWorkArea.Patient.SystemCreatePatient;
import userinterface.SystemWorkArea.Patient.SystemUpdatePatient;
import userinterface.SystemWorkArea.Patient.SystemViewPatient;

/**
 *
 * @author shriyapandita
 */
public class SystemEncountersWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemPatient
     */
    public SystemEncountersWorkPanel() {
        initComponents();
        
        SystemViewEncounter systemViewEncounter = new SystemViewEncounter();
        tabPatient.setComponentAt(0, systemViewEncounter);
        tabPatient.setTitleAt(0, "View Encounter");
        
        SystemCreateEncounter systemCreateEncounter = new SystemCreateEncounter();
        tabPatient.setComponentAt(1, systemCreateEncounter);
        tabPatient.setTitleAt(1, "Create Encounter");
        
        SystemUpdateEncounter systemUpdateEncounter = new SystemUpdateEncounter();
        tabPatient.setComponentAt(2, systemUpdateEncounter);
        tabPatient.setTitleAt(2, "Update Encounter");
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPatient = new javax.swing.JTabbedPane();
        tabViewPatient = new javax.swing.JPanel();
        tabCreatePatient = new javax.swing.JPanel();
        tabUpdatePatient = new javax.swing.JPanel();

        setBackground(new java.awt.Color(160, 132, 202));

        tabPatient.setBackground(new java.awt.Color(191, 172, 224));

        javax.swing.GroupLayout tabViewPatientLayout = new javax.swing.GroupLayout(tabViewPatient);
        tabViewPatient.setLayout(tabViewPatientLayout);
        tabViewPatientLayout.setHorizontalGroup(
            tabViewPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        tabViewPatientLayout.setVerticalGroup(
            tabViewPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tabPatient.addTab("tab1", tabViewPatient);

        javax.swing.GroupLayout tabCreatePatientLayout = new javax.swing.GroupLayout(tabCreatePatient);
        tabCreatePatient.setLayout(tabCreatePatientLayout);
        tabCreatePatientLayout.setHorizontalGroup(
            tabCreatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        tabCreatePatientLayout.setVerticalGroup(
            tabCreatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tabPatient.addTab("tab2", tabCreatePatient);

        javax.swing.GroupLayout tabUpdatePatientLayout = new javax.swing.GroupLayout(tabUpdatePatient);
        tabUpdatePatient.setLayout(tabUpdatePatientLayout);
        tabUpdatePatientLayout.setHorizontalGroup(
            tabUpdatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        tabUpdatePatientLayout.setVerticalGroup(
            tabUpdatePatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        tabPatient.addTab("tab3", tabUpdatePatient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPatient)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPatient)
        );

        tabPatient.getAccessibleContext().setAccessibleName("tabPatient");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel tabCreatePatient;
    private javax.swing.JTabbedPane tabPatient;
    private javax.swing.JPanel tabUpdatePatient;
    private javax.swing.JPanel tabViewPatient;
    // End of variables declaration//GEN-END:variables
}
