/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import employeedetails.Employeehistory;
import employeedetails.Employeeinfo;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.ImageIcon;
import java.awt.HeadlessException;
import java.awt.event.KeyListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author shriyapandita
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    // pushing whole reference to vital sign history
    Employeehistory history;
    public CreateJPanel(Employeehistory history) {
        
        initComponents();
        this.history = history;
        
        lblPhotoUrl.setVisible(false);
       
       
        
        // pushing the data 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblGender3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblPosition = new javax.swing.JLabel();
        lblTeam = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTeam = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        btnPhoto = new javax.swing.JButton();
        lblPhotoUrl = new javax.swing.JLabel();
        lblFileName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        ComboBoxGender = new javax.swing.JComboBox<>();
        ComboBoxLevel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        lblName.setText("Employee Name");

        lblID.setText("Employee ID");

        lblAge.setText("Age");

        lblGender.setText("Gender");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblDate.setText("Employee Start Date");

        lblLevel.setText("Employee Level");

        lblPosition.setText("Position Title");

        lblTeam.setText("Team Info");

        lblPhone.setText("Contact number");

        lblEmail.setText("Email ID");

        lblPhoto.setText("Photo");

        btnPhoto.setText("Choose Photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setText("CREATE EMPLOYEE FORM");

        ComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female ", "Other" }));
        ComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGenderActionPerformed(evt);
            }
        });

        ComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Associate Software Engineer", "Software Engineer", "Senior Software Engineer", "Associate Manager", "Manager", "Senior Manager", " " }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("(Enter  MM/DD/YYYY)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(442, 442, 442))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPhoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPhotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtTeam)
                            .addComponent(txtPhone)
                            .addComponent(txtEmail))
                        .addGap(241, 241, 241)))
                .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate)
                            .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblGender3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ComboBoxGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender)
                    .addComponent(ComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLevel)
                    .addComponent(ComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTeam)
                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPosition)
                        .addGap(6, 6, 6)
                        .addComponent(lblGender3)
                        .addGap(18, 18, 18)
                        .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPhoto)
                                .addComponent(btnPhoto))
                            .addComponent(lblPhotoUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnSave)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
        
        //first extract information:
        
       // 
       // use this to create new data and add to the history 
       // not manually add to array list. add new method to the emp history 
        
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Employeeinfo ei = history.addNewEmployee();
        
        try{
            
                String employeeId = txtId.getText();
                String employeeName = txtName.getText();
                int age = Integer.parseInt(txtAge.getText());            
                String gender = ComboBoxGender.getSelectedItem().toString();
                String startDate = txtDate.getText();

                String dateRegex = "^(1[0-2]|0[1-9])/(3[01]" + "|[12][0-9]|0[1-9])/[0-9]{4}$";
                Pattern pattern = Pattern.compile(dateRegex);
                Matcher matcher = pattern.matcher((CharSequence)startDate);

               if(!matcher.matches())
                {
                    JOptionPane.showMessageDialog(this, "Enter Start Date as per Pattern (MM/dd/yyy)");
                    return;  
                }
           
                
               
            
                String level = ComboBoxLevel.getSelectedItem().toString();
                String teamInfo = txtTeam.getText();
                String positionTitle = txtPosition.getText();

                String contactnumberRegex = "\\d{10}";  
                long contactnumber = Long.parseLong(txtPhone.getText());
            

                if(!txtPhone.getText().matches(contactnumberRegex))
                {
                    JOptionPane.showMessageDialog(this, "Enter Valid Cell Phone Number!");
                    return;
                }

                 String emailRegex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
                 String emailAddress = txtEmail.getText();
//
                 if(!emailAddress.matches(emailRegex))
                {
                    JOptionPane.showMessageDialog(this, "Enter Valid Email Address!");
                    return;
                }     
          
                ImageIcon photo = new ImageIcon(lblPhotoUrl.getText());
                
               // String NumRegex = "[0-9]+";
                
           
               // if(!txtAge.getText().matches(NumRegex))
              //  {
              //      JOptionPane.showMessageDialog(this, "Enter valid age");
              //      return;
             //   }
            
       
                ei.setEmployeeid(Integer.parseInt(employeeId));
                ei.setName(employeeName);
                
                ei.setGender(gender);

                Date date1;  
                try 
                {
                    date1 = new SimpleDateFormat("MM/dd/yyyy").parse(startDate);
                
                    ei.setStartdate(date1); 
                } 
                catch (ParseException ex) 
                {
                Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }

                ei.setLevel(level);
                ei.setAge(age);
                ei.setTeaminfo(teamInfo);
                ei.setPositiontitle(positionTitle);
                ei.setContactnumber(contactnumber);
                ei.setEmail(emailAddress);
                ei.setPhoto(photo);
            
                JOptionPane.showMessageDialog(this, "Employee Details Saved Sucessfully!");
            
            }
        
        catch(HeadlessException | NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "Please check employee details and try again!");
        }
        
        txtId.setText("");
        txtName.setText("");
        txtAge.setText("");
        ComboBoxGender.setSelectedIndex(0);
        txtDate.setText("");
        ComboBoxLevel.setSelectedIndex(0);
        txtTeam.setText("");
        txtPosition.setText("");
        txtPhone.setText(""); 
        txtEmail.setText("");
        lblPhotoUrl.setText("");
        lblFileName.setText("");
        
        
        
        
        
        
        
        
        
        //String name = txtName.getText(); 
        //int id = Integer.parseInt(txtId.getText()); 
       // int age = Integer.parseInt(txtAge.getText());
       // String gender = txtGender.getText();
       // String date = txtDate.getText();
      //  String level = txtLevel.getText();
      //  String team = txtTeam.getText();
      //  String title = txtPosition.getText();
      //  int phone = Integer.parseInt(txtPhone.getText());
      //  String email = txtEmail.getText();
     //   ImageIcon photo = new ImageIcon(lblPhotoUrl.getText());
        
        
        
      //  Employeeinfo ei = history.addNewEmployee();
        
      //  ei.setName(name);
      //  ei.setEmployeeid(id);
     //   ei.setAge(age);
     //   ei.setGender(gender);
     //   ei.setStartdate(date);
     //   ei.setLevel(level);
     //   ei.setTeaminfo(team);
      //  ei.setPositiontitle(title);
     //   ei.setContactnumber(phone);
     //   ei.setEmail(email);
     //   ei.setPhoto(photo);
        
        //inform user with a message pop up after saving the details 
      //  JOptionPane.showMessageDialog(this, "New Employee record added");
        
        //clear out the text boxes after entering by settung ti enoty strungs
       /// txtId.setText("");
       // txtAge.setText("");
      //  txtGender.setText("");
      //  txtDate.setText("");
      //  txtLevel.setText("");
      //  txtTeam.setText("");
     //   txtPosition.setText("");
      //  txtPhone.setText("");
      //  txtEmail.setText("");
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here                                   
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        j.setAcceptAllFileFilterUsed(false);
        j.addChoosableFileFilter(new FileNameExtensionFilter("Images", "jpg", "png"));
        
        int r =j.showOpenDialog(null);
        
       if ( r == JFileChooser.APPROVE_OPTION){
            lblPhotoUrl.setText(j.getSelectedFile().getAbsolutePath());
            lblFileName.setText(j.getSelectedFile().getName());
        }
        
        else{
            lblPhotoUrl.setText("Image not added");
        }
    }//GEN-LAST:event_btnPhotoActionPerformed
    
      
       
                    
    private void ComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGenderActionPerformed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        // TODO add your handling code here:
        String employeeId = txtId.getText();
          if(!Employeeinfo.isNumeric(employeeId)){
            JOptionPane.showMessageDialog(this, "Please enter Employee Id in digit only!");
            txtId.setText("");
        }
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        String age = txtAge.getText();
        if(!Employeeinfo.isNumeric(age)){
            JOptionPane.showMessageDialog(this, "Please enter age in digit only!");
            txtAge.setText("");
        }
    }//GEN-LAST:event_txtAgeKeyReleased

//    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {                                          
//        // TODO add your handling code here:
//        
//        String employeeId = txtId.getText();
//        if(!Employeeinfo.isNumeric(employeeId)){
//            JOptionPane.showMessageDialog(this, "Please enter Employee Id in digit only!");
//            txtId.setText("");
//        }
      
       
    //}                                         

//    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {                                   
//        // TODO add your handling code here:
//        String age = txtAge.getText();
//        if(!Employeeinfo.isNumeric(age)){
//            JOptionPane.showMessageDialog(this, "Please enter age in digit only!");
//            txtAge.setText("");
//        }
//    }                           
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxGender;
    private javax.swing.JComboBox<String> ComboBoxLevel;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender3;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoUrl;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtTeam;
    // End of variables declaration//GEN-END:variables
}
